import type { Capability, SceneDefinition, SceneId, Handoff } from "./types";
import { createSceneTimeline } from "../scenes/timelines";
import { sceneMotionDirection } from "./motionDirection";
const cv = (
  number: number,
  name: string,
  problem: string,
  observing: string,
  explanation: string,
  result: string,
): Capability => ({ number, name, problem, observing, explanation, result });
export const capabilities = {
  core: cv(
    1,
    "Drill-core analysis",
    "What is inside this core?",
    "Scanning fractures, veins and geological boundaries.",
    "Core imagery becomes structured geological and geotechnical information, supporting consistent logging and review.",
    "Core image → structured geology. Review can scale across the archive.",
  ),
  grade: cv(
    2,
    "Ore / waste & grade mapping",
    "Which material should we mine?",
    "Reading material zones with visual and spectral imagery.",
    "Vision and spectral sensing classify ore/waste regions and grade proxies. Site calibration and assays ground the interpretation.",
    "Material boundaries support selective mining and dilution decisions.",
  ),
  fragments: cv(
    3,
    "Blast fragmentation analysis",
    "Did the blast break the rock the way we wanted?",
    "Tracing individual fragments across the muckpile.",
    "Calibrated images estimate particle-size distribution, including P20, P50 and P80: the sizes at which 20%, 50% and 80% pass.",
    "Fragmentation feedback informs digging, crusher feed and future blasts.",
  ),
  safety: cv(
    6,
    "PPE, exclusion zones & proximity",
    "A person is entering the equipment zone.",
    "Tracking worker, helmet, vest and machine movement.",
    "Vision tracks people and vehicles against exclusion boundaries. A proximity event gives the operator a chance to respond.",
    "The alert is acknowledged. The worker steps clear of the machine.",
  ),
  bucket: cv(
    4,
    "Shovel bucket / tooth / boulder monitoring",
    "Is the bucket ready to load?",
    "Inspecting tooth geometry and the oversized boulder.",
    "A shovel camera checks bucket condition and loading material. Abnormal teeth and oversize prompt inspection and loading decisions.",
    "The boulder stays behind. Suitable material enters the truck.",
  ),
  driver: cv(
    5,
    "Driver fatigue & distraction",
    "The driver’s attention is changing.",
    "Observing eye closure and head pose over time.",
    "In-cab vision interprets eye, face and head behaviour to identify fatigue or distraction events.",
    "An in-cab alert prompts the driver to refocus and follow site procedures.",
  ),
  conveyor: cv(
    7,
    "Conveyor foreign-object & oversize detection",
    "A loose tool is travelling toward the crusher.",
    "The belt camera is examining the material stream.",
    "Vision identifies tools, metal, wood, oversize and abnormal material before downstream equipment.",
    "Operator alerted → belt stopped → tool removed → material flow resumes.",
  ),
  sizing: cv(
    8,
    "Online particle-size monitoring",
    "How coarse is the material now?",
    "Segmenting normal particles, rather than boxing an anomaly.",
    "Contours across calibrated belt imagery estimate changing particle-size distribution continuously.",
    "The material stream is understood. Upstream fragmentation informs downstream control.",
  ),
  sorter: cv(
    9,
    "Optical / laser ore sorting",
    "Which rocks deserve further processing?",
    "Scanning individual particles with optical and spectral sensors.",
    "Classify each particle, then time the air jet to separate selected material from the reject stream.",
    "Two physical paths. Less waste continues into processing.",
  ),
  froth: cv(
    10,
    "Flotation froth monitoring",
    "What is the froth telling us?",
    "Reading bubbles, motion, texture and stability over time.",
    "A camera above the flotation cell observes temporal froth behaviour and produces process signals for operators.",
    "Recovery conditions become visible for process review and control.",
  ),
  survey: cv(
    11,
    "Drone 3D survey / stockpile / stope inspection",
    "How much material is here, and what has changed?",
    "Matching features across overlapping imagery.",
    "Image-based reconstruction creates a point cloud, then a mesh for volume, geometry and change review. Underground void inspection uses suitable capture equipment.",
    "The site is reconstructed. Stockpile and terrain geometry can be reviewed.",
  ),
  thermal: cv(
    12,
    "Thermal + visual field inspection",
    "What can’t we see in the visual image?",
    "Comparing appearance with thermal patterns and location.",
    "RGB gives visual context. Thermal imaging exposes abnormal heat regions, localised as inspection targets.",
    "A problem location is identified. Inspect the right place first.",
  ),
} satisfies Partial<Record<SceneId, Capability>>;
type Row = [
  SceneId,
  1 | 2 | 3,
  string,
  string,
  string,
  Handoff,
  number,
  ("left" | "right" | "center")?,
];
const rows: Row[] = [
  [
    "arrival",
    1,
    "Computer vision\nin mining.",
    "Follow the rock. See where vision becomes intelligence.",
    "Enter the mine",
    "road",
    1.15,
  ],
  [
    "drill",
    1,
    "Before we move\na single tonne.",
    "Begin below the surface. The drill brings the geology into view.",
    "Drill",
    "seam",
    1.3,
  ],
  [
    "core",
    1,
    "What’s inside\nthe rock?",
    "A core leaves the ground. Its smallest features tell a much bigger story.",
    "Core",
    "seam",
    2.1,
    "right",
  ],
  [
    "grade",
    1,
    "Ore or waste?",
    "The geological boundary expands into the exposed mine face.",
    "Grade",
    "seam",
    1.8,
  ],
  [
    "blast",
    1,
    "Now break it.",
    "The bench is prepared. Follow the wires to the detonator.",
    "Blast",
    "rock",
    1.6,
  ],
  [
    "fragments",
    1,
    "Was that\na good blast?",
    "The dust settles. Look at what the bench has become.",
    "Fragmentation",
    "rock",
    2.1,
  ],
  [
    "excavation",
    2,
    "The mine\nwakes up.",
    "A bucket enters the muckpile. Machines and people begin to move.",
    "Dig",
    "rock",
    0.95,
  ],
  [
    "safety",
    2,
    "Two paths.\nOne danger zone.",
    "Watch the worker and the rotating excavator. Their paths are closing.",
    "Safety",
    "rock",
    2,
    "left",
  ],
  [
    "bucket",
    2,
    "The bucket takes\nthe punishment.",
    "A damaged tooth. An oversized boulder. Look before loading.",
    "Bucket",
    "rock",
    2.8,
    "right",
  ],
  [
    "loading",
    2,
    "Follow the rock.",
    "The bucket swings. The same fragments fall into the truck bed.",
    "Load",
    "road",
    1.05,
  ],
  [
    "haul",
    2,
    "The long haul.",
    "Across benches and winding roads, the material keeps moving.",
    "Haul",
    "road",
    1.15,
  ],
  [
    "driver",
    2,
    "Inside the cab.",
    "Repetition and time change the driver’s attention.",
    "Driver",
    "road",
    2,
    "left",
  ],
  [
    "crusher",
    2,
    "From tonnes\nto flow.",
    "The bed tips. Follow the load down through the crusher.",
    "Crush",
    "rock",
    1.5,
  ],
  [
    "conveyor",
    2,
    "Something\ndoesn’t belong.",
    "A maintenance tool falls. The belt carries it toward critical equipment.",
    "Convey",
    "belt",
    3.3,
  ],
  [
    "sizing",
    2,
    "Is the rock\nthe right size?",
    "The tool is gone. Now look closely at the normal material stream.",
    "Size",
    "belt",
    1.9,
  ],
  [
    "sorter",
    3,
    "Every rock\nbecomes a decision.",
    "One belt arrives. Two material paths leave.",
    "Sort",
    "rock",
    2,
  ],
  [
    "slurry",
    3,
    "The rock\ndisappears.",
    "Selected material is ground finer and joins water as slurry.",
    "Process",
    "water",
    0.95,
  ],
  [
    "froth",
    3,
    "Can you read\nthe froth?",
    "Slow down. The surface carries information about the process beneath.",
    "Recover",
    "water",
    2.2,
    "right",
  ],
  [
    "stockpile",
    3,
    "From process\nto product.",
    "Pull out of the plant. Accumulated material brings us back to mine scale.",
    "Stockpile",
    "drone",
    1.05,
  ],
  [
    "survey",
    3,
    "How much\nis actually there?",
    "Rise with the drone. Doodle terrain becomes points, then a mesh.",
    "Survey",
    "drone",
    2.5,
  ],
  [
    "thermal",
    3,
    "Some problems\nare invisible.",
    "The same landscape, observed through another sensor.",
    "Inspect",
    "drone",
    2,
  ],
  [
    "finale",
    3,
    "One operation.\nMany visual decisions.",
    "Turn the CV layer off, then on. The operation stays the same; only what we can see changes.",
    "Whole mine",
    "drone",
    3.5,
  ],
];
export const sceneRegistry: SceneDefinition[] = rows.map(
  ([id, part, title, subtitle, stage, handoff, scrollLength, anchor]) => ({
    id,
    part,
    title,
    subtitle,
    stage,
    handoff,
    scrollLength: sceneMotionDirection[id]?.desktopLength ?? scrollLength,
    mobileLength: sceneMotionDirection[id]?.mobileLength ?? Math.max(0.6, scrollLength * 0.7),
    anchor: anchor ?? "center",
    capability: capabilities[id as keyof typeof capabilities],
    desktopTimeline: createSceneTimeline(id),
    mobileTimeline: createSceneTimeline(id),
  }),
);
export const sceneById = Object.fromEntries(
  sceneRegistry.map((s) => [s.id, s]),
) as Record<SceneId, SceneDefinition>;
export const partNames = [
  "Reading the rock & breaking the bench",
  "Moving the mountain",
  "Turning ore into value & seeing the whole mine",
];
